### ISSUE TITLE
Expose treeInterpreter.Execute

### ISSUE THREAD

**Issue by highlyunavailable** [jmespath/go-jmespath#12]
I'm building something that seems like it would be a good fit for JMES, but where JMES paths are pre-configured and then used to filter multiple (thousands of) distinct JSON objects of the same JSON "schema" that come in over time - e.g. journalctl output. To avoid re-lexing and re-parsing the path every single operation (which won't be changing), it would be nice to "compile" the AST from a config file's JMES path, then just send it to treeInterpreter.Execute over and over.

I'd be happy to do the work (probably exposing it as `jmespath.SearchParsed(expression *ASTNode, data interface{}) (interface{}, error)` or something similar) if a pull request would be accepted.

**Comment by jamesls** [comment]
Hi, sorry for the late response.  I think this would be a good feature to add.

Another possible way to address this is to have a parse function that returns some object which internally holds the parsed result.  It would then have a `Search` method exposed on it.  Similar to regexp's `MustCompile()/MatchString()`.  Maybe:

```
expr := jmespath.MustCompile("foo.bar[0]")
result, err := expr.Search(...)
```

The benefit here is there's freedom to change the internals of the interpreter.  I'm looking into possibly not walking the AST and instead generating bytecode, and this would allow the transition transparent to users if this were to happen because we're not exposing `ASTNode`.

**Comment by highlyunavailable** [comment]
That's an even better way. I made a PR with this method - there are a few questions I had about it as well that I put in the PR.
